services:
  postgres:
    image: postgres:15
    container_name: cpp_batch_postgres
    environment:
      POSTGRES_USER: batch_user
      POSTGRES_PASSWORD: batch_pass
      POSTGRES_DB: batch_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
